spring:
  application:
    name: order
  datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 111111
        url: jdbc:mysql://localhost:3306/sell?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
