spring:
  datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 111111
        url: jdbc:mysql://localhost:3306/sell?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  jpa:
    show-sql: true
  redis:
    port: 6379
    host: localhost
